### ISSUE TITLE
 Handle REDCap timestamps set to '[not completed]'

### ISSUE THREAD

**Issue by cborromeo** [dbmi-pitt/path-redcap-to-cdm#11]
The REDCap forms will occasionally report a timestamp as '[not completed]' instead of giving it a real timestamp. These appear in the log file as:

Error converting REDCap timestamp [not completed]. Error time data '[not completed]' does not match format '%Y-%m-%d %H:%M:%S'

Instead of logging the message, the code should simply ignore the date if it is equal to the string '[not completed]'.

**Comment by cborromeo** [comment]
I added text to the log file to track the fact that these forms were skipped:

2018-07-05 14:05:43,006: INFO - Skipped 2184 forms for project IPF because of invalid form timestamps.

**Comment by cborromeo** [comment]
@nkc7 @shirey We need to discuss this issue with Harold and Mark.  We are dropping a decent number of forms since they lack timestamps.  This means the PRO_CM table will have less data.  I think the PaTH researchers may want these forms in spite of the lack of timestamp.  We should discuss if we need to build a PATH_PRO_CM.

**Comment by cborromeo** [comment]
@shirey, @nkc7 please review this and confirm:

The solution we discussed is as follows:
- add a column to the PRO_CM table called DATE_MISSING this is a varchar2(1) field.  It will contain a T or F.  T indicates the date in the PRO_DATE column is not the actual date for the form.
- If DATE_MISSING is T, insert Jan 1, 1900 for the PRO_DATE for this record.

**Comment by shirey** [comment]
This is what was discussed on the iStrat call.  @nkc7 Do you think this needs to be run past PCORI/PCRF before we implement?

**Comment by nkc7** [comment]
@shirey sent email to PCORI.. will let you know..
