### ISSUE TITLE
Re-run Redcap code

### ISSUE THREAD

**Issue by cborromeo** [dbmi-pitt/path-redcap-to-cdm#17]
Chuck – Allan just copied the ‘new’ cdm_41_etl  to dbprod02 from Neptune… and I forgot tohave him preserve the PRO_CM table.
 
Sometime this week or early next week (just tell me when), Can you re-run the redcap scripts into that table?  Also – please leave out the patient with id: PITNone
And make sure to put PIT in front of the ids.

**Comment by nkc7** [comment]
@shirey @cborromeo can we have this be in sprint starting tomorrow?

**Comment by cborromeo** [comment]
@nkc7 I loaded the data into the CDM_41_ETL.PRO_CM table.  Please review.
